### ISSUE TITLE
SQLite Database Connection Error - LogCat (Might help with database reconfiguration)

### ISSUE THREAD

**Issue by skhati1** [skhati1/442_BWK#13]
05-10 10:29:24.462: E/pokedroid(15569): android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
05-10 10:30:27.582: E/pokedroid(15569): android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
05-10 10:30:27.592: E/pokedroid(15569): android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
05-10 10:30:27.782: E/AndroidRuntime(15569): FATAL EXCEPTION: AsyncTask #1
05-10 10:30:27.782: E/AndroidRuntime(15569): Process: com.games.pokedroid, PID: 15569
05-10 10:30:27.782: E/AndroidRuntime(15569): java.lang.RuntimeException: An error occured while executing doInBackground()
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at android.os.AsyncTask$3.done(AsyncTask.java:300)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at java.lang.Thread.run(Thread.java:818)
05-10 10:30:27.782: E/AndroidRuntime(15569): Caused by: java.lang.StackOverflowError: stack size 1036KB
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at java.util.WeakHashMap$Entry.<init>(WeakHashMap.java:71)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at java.util.WeakHashMap.put(WeakHashMap.java:611)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at android.database.sqlite.SQLiteConnectionPool.finishAcquireConnectionLocked(SQLiteConnectionPool.java:911)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at android.database.sqlite.SQLiteConnectionPool.tryAcquirePrimaryConnectionLocked(SQLiteConnectionPool.java:847)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:613)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:586)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1255)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.SQLSource.getIntList(SQLSource.java:74)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.getIntList(Pokemon.java:971)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:382)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemon.java:389)
05-10 10:30:27.782: E/AndroidRuntime(15569): 	at com.games.pokedroid.game.Pokemon.FillMovepool(Pokemo

**Comment by skhati1** [comment]
This appeared when trying to simply run a quick battle.
